### ISSUE TITLE
differnt figure plotted when running mc.py

### ISSUE THREAD

**Issue by zhiyunq** [timbmg/easy21#1]
Here is what I got from running mc.py unmodified:

![image](https://user-images.githubusercontent.com/10407469/52424880-ba045400-2aaf-11e9-8e22-b4ab83be7b75.png)

Any idea why it would be different?

**Comment by zhiyunq** [comment]
OK. Found the bug which caused the issue: it is in environment.py

if np.random.random() <= 1/3:

The condition is always false because 1/3 is evaluated to 0. So effectively the card values are never negative as described in the game rules.

Changing it to the following will generate the correct figure:

if np.random.random() <= 1.0/3:

**Comment by zhiyunq** [comment]
One more update:

In python 3.0,  1/3 does evaluate to 0.3333...

I was using python 2.7.6, which evaluates to 1/3 to 0 apparently. Surprised to see this behavior discrepancy in python (still new to it).

**Comment by timbmg** [comment]
Right. Do you get a similar plot with python3?

**Comment by zhiyunq** [comment]
Actually I don't have python3. But after changing "1/3" to "1.0/3" the plot changes to what you have.
